Дроны умеют стрелять и лечиться
suguby/astrobox pull request #2
Opened 2018-10-31 16:09 UTC by theg4sh

Так же дроны лечаться от материнского корабля.

2018-11-06 20:46 UTC, suguby requested changes

2018-11-06 20:46 UTC, suguby commented on astrobox/guns.py
> +        # Пролетаем свои и некомандные объекты
свои тоже надо взрывать - френдли файр возможен

2018-11-06 20:46 UTC, suguby commented on demo/game.py
> +sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..', 'robogame_engine')))
sys.path.append - не нужно магии, настрой свой проект так что бы пути поиска были правильные.

2018-11-06 20:46 UTC, suguby commented on demo/game.py
> +        team_drone_classes=[WorkerDron, GreedyDron, HunterDron, DestroyerDron],
А как сделать что бы команда дронов была  N штук? я не совсем понимаю зачем в SpaceField передавать классы дронов.
было же просто workers = [WorkerDron() for _ in range(N)] и всё, класс дрона сам себя в SpaceField регил... верни, что бы так же осталось - так уже записали лекции студентам.

2018-11-06 20:46 UTC, suguby commented on demo/game.py
> +        team_drone_classes=[WorkerDron, GreedyDron, HunterDron, DestroyerDron],
счас у меня одна команда просто выносит все базы по очереди, а потом начинает летать между пустыми астероидами. Сделай что бы они за чужими дронами гонялись сначала.

2018-11-06 20:46 UTC, suguby commented on astrobox/units.py
> +class DroneUnit(Unit):
Тоже не совсем ясно зачем Dron в DronUnit переименовал - надо оставить старый интерфейс классов.

2018-11-06 20:46 UTC, suguby commented on astrobox/units.py
> +        return self.__health / theme.MOTHERSHIP_MAX_SHIELD
переименуй на meter_2 - первый отображает элериум, второй - шелду.

2018-11-06 20:46 UTC, suguby commented on astrobox/units.py
> +class DroneUnit(Unit):
В курсе нужно поддержать этапность - сначала без стрельбы, потом со стрельбой. 
По умолчанию дроны не умеют стрелять. А потом надо уметь включить эту фичу. Наверно параметр базового класса Drone.fighting=True сделать. При запуске игры меняем параметр класса и создаем дронов.

2018-11-06 20:46 UTC, suguby commented on astrobox/units.py
> +class DroneUnit(Unit):
Это на обсуждение - напиши как можно сделать

2018-11-06 20:46 UTC, suguby commented on astrobox/space_field.py
> +    def prepare(self, asteroids_count=5, team_drone_classes=[]):
не надо  team_drone_classes передавать сюда!
BTW, нельзя дефолтным параметром делать изменяемый обьект! Только None, а в коде if team_drone_classes is None ... и так далее.

2018-11-06 20:46 UTC, suguby commented on astrobox/units.py
> +from .cargo import *
не надо import * - пропиши конкретно что портируется - хороший стиль.

2018-11-12 19:44 UTC, theg4sh commented on demo/game.py
> +        team_drone_classes=[WorkerDron, GreedyDron, HunterDron, DestroyerDron],
> что бы команда дронов была N штук?

Вообще была добавлена константа TEAM_DRONES_COUNT. Но попробую вернуть как было.

> летать между пустыми астероидами

Это не так, если есть что-то, что остается в астероидах, они собирают их. Да есть механизм в HarvestingStrategy, чтобы дрон создавал видимость работы если собирать уже нечего.

> Сделай что бы они за чужими дронами гонялись сначала.

А это действительно нужно? До этого были просто `RunnerDron`-ы которые вообще ничего не делали.

2018-11-12 19:44 UTC, theg4sh commented on astrobox/units.py
> +class DroneUnit(Unit):
> Тоже не совсем ясно зачем Dron в DronUnit переименовал

Как минимум потому, что Dron - слово с опечаткой, как в общем-то было с `mathership`. DroneUnit - дает целостное понимание об объекте, что это за объект и что он является объектом для Scene. Морально меня устроит вариант объявления `class Dron(DroneUnit): pass`.

Предлагаю сделать cконстанту `DRONES_CAN_FIGHT=True` в theme и использовать ее для переключения режима.

2018-11-12 19:44 UTC, theg4sh commented on astrobox/guns.py
> +        # Пролетаем свои и некомандные объекты
Сделал опционально через аттрибут `friendly_fire`.

2018-11-13 17:06 UTC, suguby requested changes
демо игра не запускается https://youtu.be/En-tZqgVPPw
:( 
начал дебажить -
astrobox/astrobox/space_field.py:124
uniqueDroneClass = list(set([drone.__class__ for drone in self.drones]))
странно определяются команды дронов - есть же self.teams

astrobox/astrobox/units.py:48 
kwargs['team'] = self.scene.get_team(self.__class__) - строка не нужна. 
(как мне коменты оставить прямо к коду в гитхабе?)

2018-11-13 17:06 UTC, suguby commented on astrobox/units.py
> +
нужно Drone - e в конце
astrobox.space_field.SpaceField#drones - тоже исправить надо

2018-11-13 17:14 UTC, theg4sh commented
> как мне коменты оставить прямо к коду в гитхабе?

Перейти на вкладку Files и навести мышь на номер строки, появится "+", далее оставить комментарий через ревью (можно разом несколько) или через кнопку "Add Single comment"

2018-11-13 17:15 UTC, theg4sh commented on astrobox/units.py
> +
> astrobox.space_field.SpaceField#drones - тоже исправить надо

Это будет безсмысленное изменение. Dron(e) итак попадет в список по родительскому классу.

2018-11-13 17:47 UTC, theg4sh commented
> демо игра не запускается

Это странно, потому что у меня все хорошо. Вы обновились до свежего кода robogame_engine ?

2018-11-13 18:21 UTC, suguby commented
Traceback (most recent call last):
  File "/home/wad/Skillbox/theg4sh/astrobox/demo/game.py", line 247, in <module>
    space_field.go()
  File "/home/wad/Skillbox/theg4sh/robogame_engine/robogame_engine/scene.py", line 170, in go
    self.game_step()
  File "/home/wad/Skillbox/theg4sh/robogame_engine/robogame_engine/scene.py", line 92, in game_step
    obj.game_step()
  File "/home/wad/Skillbox/theg4sh/astrobox/demo/game.py", line 228, in game_step
    super(DestroyerDron, self).game_step()
  File "/home/wad/Skillbox/theg4sh/astrobox/demo/game.py", line 32, in game_step
    s.game_step()
  File "/home/wad/Skillbox/theg4sh/astrobox/demo/strategies.py", line 198, in game_step
    self.__substrategy = StrategyApproachAndUnload(unit=self.unit, target_unit=self.unit.mothership());
  File "/home/wad/Skillbox/theg4sh/astrobox/demo/strategies.py", line 152, in __init__
    StrategyApproach(unit=unit, target_point=target_unit.coord, distance=distance),
AttributeError: 'NoneType' object has no attribute 'coord'

клонировал свой robogame_engine:master , включил в проект - все равно ошибка.

2018-11-13 18:22 UTC, suguby commented
насколько я понимаю - команда не определяется, поэтому нет картинки базы, а как только дроны собираются домой лететь - ошибка, у них вместо дома - None

2018-11-15 21:43 UTC, theg4sh commented
@suguby Прежде чем проверять перемещение, нужно подтянуть изменения https://github.com/suguby/robogame_engine/pull/7

2018-11-16 13:47 UTC, merged